# Versioning System
DU_BASE_VERSION = EXTRASAFE
DU_BUILD_TYPE := DUREX

# Set all versions
TARGET_PRODUCT_SHORT := $(subst du_,,$(DU_BUILD_TYPE))
DU_DATE := $(shell date -u +%d-%m-%Y)
DATE := $(shell date -u +%Y%m%d)
TIME := $(shell date -u +%H%M)
DU_BUILD_VERSION := $(DU_BUILD_TYPE)-$(DU_BASE_VERSION)-$(DATE)-$(TIME)
DU_VERSION := $(DU_BUILD_TYPE)-$(DU_BASE_VERSION)-$(DU_BUILD)-$(DATE)-$(TIME)
TARGET_BACON_NAME := $(DU_VERSION)
ROM_FINGERPRINT := DirtyUnicorns/$(PLATFORM_VERSION)/$(DU_BUILD_TYPE)/$(DATE)$(TIME)

export DU_BASE_VERSION
export DU_BUILD_VERSION
export DU_BUILD_TYPE
export DU_DATE
export DU_VERSION
export ROM_FINGERPRINT
